# Generated by Django 4.0.2 on 2023-03-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'default_related_name': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='moviesession',
            options={'default_related_name': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'default_related_name': 'orders', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_related_name': 'tickets'},
        ),
    ]
