# Generated by Django 4.0.2 on 2022-11-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "db",
            "0002_user_order_ticket_alter_moviesession_cinema_hall_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "movie_session"),
                name="unique_row_seat_session",
            ),
        ),
    ]
