# Generated by Django 4.0.2 on 2024-02-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creat_at',
            new_name='created_at',
        ),
    ]
