# Generated by Django 4.0.2 on 2023-09-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_movie_title_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
