# Generated by Django 4.0.2 on 2024-01-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_order_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
