# Generated by Django 4.0.2 on 2023-11-30 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 10, 14, 40)),
        ),
    ]
