# Generated by Django 4.0.2 on 2023-03-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_order_alter_movie_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
