# Generated by Django 4.0.2 on 2023-11-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticked_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticked',
            new_name='Ticket',
        ),
    ]
