# Generated by Django 4.0.2 on 2022-06-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_alter_movie_title_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'movie_session')},
        ),
    ]
