# Generated by Django 4.0.2 on 2023-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='db_movie_title_5d0841_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_seat_in_movie_session'),
        ),
    ]
