# Generated by Django 4.0.2 on 2022-12-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_movie_db_movie_title_5d0841_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
