# Generated by Django 4.0.2 on 2022-11-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='user',
        ),
    ]
