# Generated by Django 4.0.2 on 2023-10-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_user_order_ticket_alter_movie_actors_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "movie_session"), name="unique_ticket"
            ),
        ),
    ]
