# Generated by Django 4.0.2 on 2023-10-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_use654567'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Use654567',
        ),
    ]
