# Generated by Django 4.0.2 on 2023-07-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_ticket_movie_db_movie_title_5d0841_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.moviesession'),
        ),
    ]
