# Generated by Django 4.0.2 on 2024-07-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'movie_session')},
        ),
    ]
