# Generated by Django 4.0.2 on 2024-09-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_movie_session',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='movie_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='db.moviesession'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'row', 'seat'), name='unique_ticket_row_seat_session'),
        ),
    ]
