# Generated by Django 4.0.2 on 2024-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_order_user_ticket_ticket_unique_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
