
# Generated by Django 4.0.2 on 2022-11-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_moviesession_cinema_hall_ticket_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
