# Generated by Django 4.0.2 on 2024-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_ticket_unique_ticket_seat_movie_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_seat_movie',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat', 'row', 'movie_session'), name='unique_ticket_seat_row'),
        ),
    ]
