# Generated by Django 4.0.2 on 2022-10-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
    ]
