# Generated by Django 4.0.2 on 2023-03-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_movie_created_at_alter_movie_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
    ]
