# Generated by Django 5.1.2 on 2024-10-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
