# Generated by Django 4.0.2 on 2024-06-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
