# Generated by Django 4.0.2 on 2023-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_ticket_ticketuniqueconstraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='TicketUniqueConstraint',
        ),
    ]
