# Generated by Django 4.0.2 on 2023-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_order_user_ticket_ticket_unic_seat_and_row"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
