# Generated by Django 5.1.2 on 2024-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_actor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='db_movie_title_5d0841_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
