# Generated by Django 4.0.2 on 2024-01-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_ticket_unique_movie_session_row_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
