# Generated by Django 4.0.2 on 2022-11-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
