# Generated by Django 4.0.2 on 2022-10-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
