# Generated by Django 4.0.2 on 2023-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_ticket_ticket_unique_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
