# Generated by Django 4.0.2 on 2024-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_user_authorization_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
