# Generated by Django 4.0.2 on 2023-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_babyla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Babyla',
        ),
    ]
