# Generated by Django 4.0.2 on 2023-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default="2023-08-22 19:03:44"),
        ),
    ]
