# Generated by Django 4.0.2 on 2024-06-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='ticket_row_seat_movie_session'),
        ),
    ]
