# Generated by Django 4.0.2 on 2023-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_ticket_unique_row_seat_movie_session_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_row_seat_movie_session',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_row_seat_movie_session'),
        ),
    ]
