# Generated by Django 4.0.2 on 2024-01-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_order_user_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='first_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
