# Generated by Django 4.0.2 on 2023-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_movie_db_movie_title_5d0841_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_ticket_row_seat_movie_session'),
        ),
    ]
