# Generated by Django 4.0.2 on 2022-03-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
    ]
