# Generated by Django 4.0.2 on 2024-09-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'seat', 'row'), name='unique_movie_session_seat_row'),
        ),
    ]
