# Generated by Django 4.0.2 on 2023-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_ticket_unique_order_row_seat_order_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='moviesession',
            name='row',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='seat',
            field=models.IntegerField(null=True),
        ),
    ]
