# Generated by Django 4.0.2 on 2023-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_delete_babyla'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
