# Generated by Django 4.1.4 on 2022-12-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_ticket_unique_ticket_ticket_unique_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-movie_session']},
        ),
    ]
