# Generated by Django 5.1.2 on 2024-10-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_movie_actors_movie_genres_alter_actor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
