# Generated by Django 4.0.2 on 2023-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_ticket_unique_ticket_row_seat_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_row_seat',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_ticket_row_seat_movie_session'),
        ),
    ]
