# Generated by Django 4.0.2 on 2022-06-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_ticket_unique_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
