# Generated by Django 4.0.2 on 2023-12-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_ticket_movie_session_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
