# Generated by Django 5.1.2 on 2024-10-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_order_options_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
