# Generated by Django 4.0.2 on 2023-04-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_seat',
        ),
    ]
