# Generated by Django 4.0.2 on 2023-03-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
