# Generated by Django 4.0.2 on 2024-09-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_ticket_movie_session_alter_ticket_row_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_seat_in_session',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'movie_session')},
        ),
    ]
