# Generated by Django 4.0.2 on 2023-03-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
