# Generated by Django 4.0.2 on 2023-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_remove_ticket_unique_ticket_seat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat'), name='unique_ticket_seat'),
        ),
    ]
