# Generated by Django 4.0.2 on 2024-05-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
