# Generated by Django 4.0.2 on 2023-08-22 21:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0009_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
