# Generated by Django 4.0.2 on 2023-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movies_session'), name='row_seat_session_unique'),
        ),
    ]
