# Generated by Django 4.0.2 on 2024-05-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
    ]
