# Generated by Django 4.0.2 on 2023-03-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_ticket_row_seat_session_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='row_seat_session_unique',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='movies_session',
            new_name='movie_session',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='row_seat_session_unique'),
        ),
    ]
