# Generated by Django 4.0.2 on 2023-03-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
